name = "GasChromatographyTools"
uuid = "b1a91d42-e520-41a6-b75d-584445aea833"
authors = ["Jan Leppert <jleppert@uni-bonn.de>"]
version = "0.1.0"

[deps]
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
GasChromatographySimulator = "dd82b6e2-56ef-419d-b271-0be268cb65f5"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"

[compat]
Dierckx = "0.5"
GasChromatographySimulator = "0.1"
Interpolations = "0.13"
julia = "1.5.3"
